#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: VikyTech
email: vikytech.mail@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vikytech.site" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vikytech007
github_username:  vikytech
github: [metadata]

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Theme config
logo: /assets/img/logo.png
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]

destination: docs/

include:
  - _pages/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
